/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'rank' : IDL.Text,
  'role' : IDL.Text,
  'mainGame' : IDL.Text,
});
export const ScrimId = IDL.Nat;
export const TeamId = IDL.Nat;
export const StreamId = IDL.Nat;
export const Stream = IDL.Record({
  'title' : IDL.Text,
  'game' : IDL.Text,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'streamerName' : IDL.Text,
  'platform' : IDL.Text,
  'streamId' : StreamId,
  'streamUrl' : IDL.Text,
  'viewerCount' : IDL.Nat,
});
export const TeamView = IDL.Record({
  'members' : IDL.Vec(IDL.Principal),
  'game' : IDL.Text,
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
  'teamId' : TeamId,
});
export const ScrimView = IDL.Record({
  'title' : IDL.Text,
  'participants' : IDL.Vec(IDL.Principal),
  'teamSize' : IDL.Nat,
  'scrimId' : ScrimId,
  'game' : IDL.Text,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'platform' : IDL.Text,
  'skillLevel' : IDL.Text,
  'scheduledAt' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateProfile' : IDL.Func([UserProfile], [], []),
  'createScrim' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [ScrimId],
      [],
    ),
  'createTeam' : IDL.Func([IDL.Text, IDL.Text], [TeamId], []),
  'getAllStreams' : IDL.Func([], [IDL.Vec(Stream)], ['query']),
  'getAllTeams' : IDL.Func([], [IDL.Vec(TeamView)], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
  'getUpcomingScrims' : IDL.Func([], [IDL.Vec(ScrimView)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinTeam' : IDL.Func([TeamId], [], []),
  'leaveTeam' : IDL.Func([TeamId], [], []),
  'postStream' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [StreamId],
      [],
    ),
  'removeStream' : IDL.Func([StreamId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'signUpForScrim' : IDL.Func([ScrimId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'rank' : IDL.Text,
    'role' : IDL.Text,
    'mainGame' : IDL.Text,
  });
  const ScrimId = IDL.Nat;
  const TeamId = IDL.Nat;
  const StreamId = IDL.Nat;
  const Stream = IDL.Record({
    'title' : IDL.Text,
    'game' : IDL.Text,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'streamerName' : IDL.Text,
    'platform' : IDL.Text,
    'streamId' : StreamId,
    'streamUrl' : IDL.Text,
    'viewerCount' : IDL.Nat,
  });
  const TeamView = IDL.Record({
    'members' : IDL.Vec(IDL.Principal),
    'game' : IDL.Text,
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
    'teamId' : TeamId,
  });
  const ScrimView = IDL.Record({
    'title' : IDL.Text,
    'participants' : IDL.Vec(IDL.Principal),
    'teamSize' : IDL.Nat,
    'scrimId' : ScrimId,
    'game' : IDL.Text,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'platform' : IDL.Text,
    'skillLevel' : IDL.Text,
    'scheduledAt' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateProfile' : IDL.Func([UserProfile], [], []),
    'createScrim' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [ScrimId],
        [],
      ),
    'createTeam' : IDL.Func([IDL.Text, IDL.Text], [TeamId], []),
    'getAllStreams' : IDL.Func([], [IDL.Vec(Stream)], ['query']),
    'getAllTeams' : IDL.Func([], [IDL.Vec(TeamView)], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
    'getUpcomingScrims' : IDL.Func([], [IDL.Vec(ScrimView)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinTeam' : IDL.Func([TeamId], [], []),
    'leaveTeam' : IDL.Func([TeamId], [], []),
    'postStream' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [StreamId],
        [],
      ),
    'removeStream' : IDL.Func([StreamId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'signUpForScrim' : IDL.Func([ScrimId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };