/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ScrimId = bigint;
export interface ScrimView {
  'title' : string,
  'participants' : Array<Principal>,
  'teamSize' : bigint,
  'scrimId' : ScrimId,
  'game' : string,
  'createdBy' : Principal,
  'description' : string,
  'platform' : string,
  'skillLevel' : string,
  'scheduledAt' : bigint,
}
export interface Stream {
  'title' : string,
  'game' : string,
  'createdBy' : Principal,
  'description' : string,
  'streamerName' : string,
  'platform' : string,
  'streamId' : StreamId,
  'streamUrl' : string,
  'viewerCount' : bigint,
}
export type StreamId = bigint;
export type TeamId = bigint;
export interface TeamView {
  'members' : Array<Principal>,
  'game' : string,
  'name' : string,
  'createdBy' : Principal,
  'teamId' : TeamId,
}
export interface UserProfile {
  'username' : string,
  'rank' : string,
  'role' : string,
  'mainGame' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateProfile' : ActorMethod<[UserProfile], undefined>,
  'createScrim' : ActorMethod<
    [string, string, bigint, bigint, string, string, string],
    ScrimId
  >,
  'createTeam' : ActorMethod<[string, string], TeamId>,
  'getAllStreams' : ActorMethod<[], Array<Stream>>,
  'getAllTeams' : ActorMethod<[], Array<TeamView>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUpcomingScrims' : ActorMethod<[], Array<ScrimView>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinTeam' : ActorMethod<[TeamId], undefined>,
  'leaveTeam' : ActorMethod<[TeamId], undefined>,
  'postStream' : ActorMethod<
    [string, string, string, string, string, string, bigint],
    StreamId
  >,
  'removeStream' : ActorMethod<[StreamId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'signUpForScrim' : ActorMethod<[ScrimId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];